import 'dotenv/config'
import express from 'express'
import cors from 'cors'
import bcrypt from 'bcryptjs'
import jwt from 'jsonwebtoken'
import mongoose from 'mongoose'
import crypto from 'node:crypto'
import nodemailer from 'nodemailer'

const app = express(); const allowedOrigins = (process.env.CLIENT_URL || 'http://localhost:5173').split(',').map((origin) => origin.trim()); app.use(cors({ origin: (origin, callback) => !origin || allowedOrigins.includes(origin) || ['http://localhost:5173', 'http://127.0.0.1:5173'].includes(origin) ? callback(null, true) : callback(new Error('Origin not allowed')) })); app.use(express.json())
const PORT = process.env.PORT || 5000; const JWT_SECRET = process.env.JWT_SECRET || 'development-secret-change-me'
const users = []; const tasks = []; const invitations = []
const userSchema = new mongoose.Schema({ name: String, email: { type: String, unique: true }, password: String, role: { type: String, enum: ['ADMIN', 'MANAGER', 'EMPLOYEE'], default: 'EMPLOYEE' }, active: { type: Boolean, default: true } }, { timestamps: true })
const taskSchema = new mongoose.Schema({ title: { type: String, required: true, trim: true }, description: { type: String, required: true, trim: true }, assignedTo: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true }, createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true }, priority: { type: String, enum: ['LOW', 'MEDIUM', 'HIGH', 'URGENT'], default: 'MEDIUM' }, status: { type: String, enum: ['TODO', 'IN_PROGRESS', 'COMPLETED', 'OVERDUE'], default: 'TODO' }, deadline: { type: Date, required: true } }, { timestamps: true })
taskSchema.index({ status: 1, priority: 1, deadline: 1, assignedTo: 1 }); const invitationSchema = new mongoose.Schema({ name: { type: String, required: true, trim: true }, email: { type: String, required: true, lowercase: true, index: true }, role: { type: String, enum: ['ADMIN', 'MANAGER', 'EMPLOYEE'], required: true }, tokenHash: { type: String, required: true, unique: true, index: true }, status: { type: String, enum: ['PENDING', 'ACCEPTED', 'EXPIRED', 'CANCELLED'], default: 'PENDING', index: true }, expiresAt: { type: Date, required: true, index: true }, invitedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true }, acceptedAt: Date }, { timestamps: true }); const User = mongoose.model('User', userSchema); const Task = mongoose.model('Task', taskSchema); const Invitation = mongoose.model('Invitation', invitationSchema)
let mongo = false
const mailer = process.env.EMAIL_HOST ? nodemailer.createTransport({ host: process.env.EMAIL_HOST, port: Number(process.env.EMAIL_PORT || 587), secure: Number(process.env.EMAIL_PORT) === 465, auth: process.env.EMAIL_USER ? { user: process.env.EMAIL_USER, pass: process.env.EMAIL_PASSWORD } : undefined }) : null
const frontendUrl = process.env.FRONTEND_URL || process.env.CLIENT_URL || 'http://localhost:5173'
const hashInvitationToken = (token) => crypto.createHash('sha256').update(token).digest('hex')
const invitationView = (invitation) => ({ id: invitation._id || invitation.id, name: invitation.name, email: invitation.email, role: invitation.role, status: invitation.status, expiresAt: invitation.expiresAt, invitedBy: invitation.invitedBy?.name || invitation.invitedBy, createdAt: invitation.createdAt, acceptedAt: invitation.acceptedAt })
const sendInvitationEmail = async ({ name, email, role, token }) => { const url = `${frontendUrl}/accept-invite?token=${encodeURIComponent(token)}`; if (!mailer) return url; await mailer.sendMail({ from: process.env.EMAIL_FROM || process.env.EMAIL_USER, to: email, subject: "You've been invited to join Task Management System", text: `Hello ${name},\n\nYou have been invited to join the Task Management System as a ${role}.\n\nAccept your invitation: ${url}\n\nInvitation expires in 24 hours.`, html: `<p>Hello ${name},</p><p>You have been invited to join the Task Management System as a <strong>${role}</strong>.</p><p><a href="${url}">Accept Invitation</a></p><p>Invitation expires in 24 hours.</p>` }); return null }
const publicUser = (user) => ({ id: user._id || user.id, name: user.name, email: user.email, role: user.role, active: user.active })
const tokenFor = (user) => jwt.sign({ id: user._id || user.id, role: user.role }, JWT_SECRET, { expiresIn: '7d' })
const seedDevelopmentStore = async () => {
	if (users.length) return
	const password = await bcrypt.hash('Northstar123!', 12)
	users.push(
		{ id: 'admin-demo', name: 'Alex Morgan', email: 'admin@northstar.io', password, role: 'ADMIN', active: true },
		{ id: 'manager-demo', name: 'Jordan Lee', email: 'manager@northstar.io', password, role: 'MANAGER', active: true },
		{ id: 'employee-demo', name: 'Taylor Kim', email: 'employee@northstar.io', password, role: 'EMPLOYEE', active: true },
	)
	tasks.push(
		{ id: 'task-launch-brief', title: 'Prepare launch brief', description: 'Align the launch brief with current customer insights.', assignedTo: 'employee-demo', createdBy: 'manager-demo', priority: 'HIGH', status: 'IN_PROGRESS', deadline: new Date(Date.now() + 86400000 * 4), createdAt: new Date(), updatedAt: new Date() },
		{ id: 'task-quarterly-report', title: 'Review quarterly report', description: 'Review KPI definitions before the planning meeting.', assignedTo: 'manager-demo', createdBy: 'admin-demo', priority: 'MEDIUM', status: 'TODO', deadline: new Date(Date.now() + 86400000 * 7), createdAt: new Date(), updatedAt: new Date() },
	)
}
const auth = async (req, res, next) => { try { const header = req.headers.authorization; if (!header?.startsWith('Bearer ')) return res.status(401).json({ message: 'Authentication required' }); const payload = jwt.verify(header.slice(7), JWT_SECRET); req.user = mongo ? await User.findById(payload.id) : users.find((user) => user.id === payload.id); if (!req.user) return res.status(401).json({ message: 'Session expired' }); next() } catch { res.status(401).json({ message: 'Invalid or expired session' }) } }
const allow = (...roles) => (req, res, next) => roles.includes(req.user.role) ? next() : res.status(403).json({ message: 'You do not have permission for this action' })
const store = async (model, fallback) => mongo ? model : fallback
app.get('/api/health', (req, res) => res.json({ status: 'ok', database: mongo ? 'mongodb' : 'development-memory' }))
app.post('/api/auth/register', async (req, res, next) => { try { const { name, password, role = 'EMPLOYEE' } = req.body; const email = req.body.email?.trim().toLowerCase(); if (!name || !email || !password || password.length < 8) return res.status(400).json({ message: 'Name, email, and a password of at least 8 characters are required' }); if (mongo) { if (await User.findOne({ email })) return res.status(409).json({ message: 'An account with that email already exists' }); const user = await User.create({ name, email, password: await bcrypt.hash(password, 12), role }); return res.status(201).json({ user: publicUser(user), token: tokenFor(user) }) } if (users.some((user) => user.email === email)) return res.status(409).json({ message: 'An account with that email already exists' }); const user = { id: String(Date.now()), name, email, password: await bcrypt.hash(password, 12), role, active: true }; users.push(user); res.status(201).json({ user: publicUser(user), token: tokenFor(user) }) } catch (error) { next(error) } })
app.post('/api/auth/login', async (req, res, next) => { try { const email = req.body.email?.trim().toLowerCase(); const user = mongo ? await User.findOne({ email }) : users.find((item) => item.email === email); if (!user || !(await bcrypt.compare(req.body.password || '', user.password)) || user.active === false) return res.status(401).json({ message: 'Invalid email or password' }); res.json({ user: publicUser(user), token: tokenFor(user) }) } catch (error) { next(error) } })
app.get('/api/auth/me', auth, (req, res) => res.json({ user: publicUser(req.user) }))
app.get('/api/users', auth, allow('ADMIN'), async (req, res, next) => { try { res.json({ users: mongo ? (await User.find().sort({ createdAt: -1 })).map(publicUser) : users.map(publicUser) }) } catch (error) { next(error) } })
app.patch('/api/users/:id', auth, allow('ADMIN'), async (req, res, next) => { try { const allowed = { role: req.body.role, active: req.body.active }; const user = mongo ? await User.findByIdAndUpdate(req.params.id, allowed, { new: true }) : users.find((item) => item.id === req.params.id); if (!mongo && user) Object.assign(user, allowed); if (!user) return res.status(404).json({ message: 'User not found' }); res.json({ user: publicUser(user) }) } catch (error) { next(error) } })
app.post('/api/invitations', auth, allow('ADMIN'), async (req, res, next) => { try { const name = req.body.name?.trim(); const email = req.body.email?.trim().toLowerCase(); const { role } = req.body; if (!name || !/^\S+@\S+\.\S+$/.test(email || '') || !['ADMIN', 'MANAGER', 'EMPLOYEE'].includes(role)) return res.status(400).json({ message: 'A valid name, email, and role are required' }); const existing = mongo ? await User.findOne({ email }) : users.find((user) => user.email === email); if (existing) return res.status(409).json({ message: 'User with this email already exists.' }); const now = new Date(); const activeInvitation = mongo ? await Invitation.findOne({ email, status: 'PENDING', expiresAt: { $gt: now } }) : invitations.find((invitation) => invitation.email === email && invitation.status === 'PENDING' && invitation.expiresAt > now); if (activeInvitation) return res.status(409).json({ message: 'A pending invitation already exists for this email.' }); const token = crypto.randomBytes(32).toString('hex'); const invitationData = { name, email, role, tokenHash: hashInvitationToken(token), status: 'PENDING', expiresAt: new Date(now.getTime() + 24 * 60 * 60 * 1000), invitedBy: mongo ? req.user._id : req.user.id }; const invitation = mongo ? await Invitation.create(invitationData) : { ...invitationData, id: String(Date.now()), createdAt: now }; if (!mongo) invitations.push(invitation); try { const invitationUrl = await sendInvitationEmail({ name, email, role, token }); const response = { message: 'Invitation sent successfully' }; if (!mailer && process.env.NODE_ENV !== 'production') response.invitationUrl = invitationUrl; return res.status(201).json(response) } catch (error) { if (mongo) await Invitation.findByIdAndDelete(invitation._id); else invitations.splice(invitations.indexOf(invitation), 1); return res.status(502).json({ message: 'Invitation could not be sent. Check the email configuration and try again.' }) } } catch (error) { next(error) } })
app.get('/api/invitations', auth, allow('ADMIN'), async (req, res, next) => { try { const now = new Date(); if (mongo) { await Invitation.updateMany({ status: 'PENDING', expiresAt: { $lte: now } }, { $set: { status: 'EXPIRED' } }); return res.json({ invitations: (await Invitation.find().populate('invitedBy', 'name').sort({ createdAt: -1 })).map(invitationView) }) } invitations.forEach((invitation) => { if (invitation.status === 'PENDING' && invitation.expiresAt <= now) invitation.status = 'EXPIRED' }); res.json({ invitations: invitations.map(invitationView).sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt)) }) } catch (error) { next(error) } })
app.delete('/api/invitations/:id', auth, allow('ADMIN'), async (req, res, next) => { try { const invitation = mongo ? await Invitation.findOneAndUpdate({ _id: req.params.id, status: 'PENDING' }, { status: 'CANCELLED' }, { new: true }) : invitations.find((item) => item.id === req.params.id && item.status === 'PENDING'); if (!mongo && invitation) invitation.status = 'CANCELLED'; if (!invitation) return res.status(404).json({ message: 'Pending invitation not found' }); res.json({ message: 'Invitation cancelled successfully' }) } catch (error) { next(error) } })
app.get('/api/invitations/verify', async (req, res, next) => { try { const tokenHash = hashInvitationToken(req.query.token || ''); const invitation = mongo ? await Invitation.findOne({ tokenHash }).select('-tokenHash') : invitations.find((item) => item.tokenHash === tokenHash); if (!invitation || invitation.status !== 'PENDING' || invitation.expiresAt <= new Date()) return res.status(400).json({ message: 'This invitation is invalid or expired.' }); res.json({ invitation: invitationView(invitation) }) } catch (error) { next(error) } })
app.post('/api/invitations/accept', async (req, res, next) => { try { const { token, password } = req.body; if (!token || !password || password.length < 8) return res.status(400).json({ message: 'A valid invitation token and password of at least 8 characters are required' }); const tokenHash = hashInvitationToken(token); const invitation = mongo ? await Invitation.findOne({ tokenHash }) : invitations.find((item) => item.tokenHash === tokenHash); if (!invitation || invitation.status !== 'PENDING' || invitation.expiresAt <= new Date()) return res.status(400).json({ message: 'This invitation is invalid or expired.' }); const existing = mongo ? await User.findOne({ email: invitation.email }) : users.find((user) => user.email === invitation.email); if (existing) return res.status(409).json({ message: 'User with this email already exists.' }); const userData = { name: invitation.name, email: invitation.email, password: await bcrypt.hash(password, 12), role: invitation.role, active: true }; if (mongo) { await User.create(userData); await Invitation.updateOne({ _id: invitation._id }, { status: 'ACCEPTED', acceptedAt: new Date() }) } else { users.push({ ...userData, id: String(Date.now()) }); invitation.status = 'ACCEPTED'; invitation.acceptedAt = new Date() } res.json({ message: 'Invitation accepted successfully' }) } catch (error) { next(error) } })
app.get('/api/tasks', auth, async (req, res, next) => { try { const query = {}; if (req.query.status) query.status = req.query.status; if (req.query.priority) query.priority = req.query.priority; if (req.query.search) query.title = { $regex: req.query.search, $options: 'i' }; if (mongo) return res.json(await Task.find(query).populate('assignedTo createdBy', 'name email').sort({ [req.query.sort || 'createdAt']: -1 })); let result = tasks.filter((task) => (!query.status || task.status === query.status) && (!query.priority || task.priority === query.priority) && (!req.query.search || task.title.toLowerCase().includes(req.query.search.toLowerCase()))); res.json(result) } catch (error) { next(error) } })
app.get('/api/tasks/my', auth, async (req, res, next) => { try { if (mongo) return res.json(await Task.find({ assignedTo: req.user._id }).populate('assignedTo createdBy', 'name email')); res.json(tasks.filter((task) => task.assignedTo === req.user.id)) } catch (error) { next(error) } })
app.get('/api/tasks/status/:status', auth, (req, res) => res.redirect(`/api/tasks?status=${req.params.status}`)); app.get('/api/tasks/priority/:priority', auth, (req, res) => res.redirect(`/api/tasks?priority=${req.params.priority}`))
app.get('/api/tasks/:id', auth, async (req, res, next) => { try { const task = mongo ? await Task.findById(req.params.id).populate('assignedTo createdBy', 'name email role') : tasks.find((item) => item.id === req.params.id); if (!task) return res.status(404).json({ message: 'Task not found' }); res.json(task) } catch (error) { next(error) } })
app.post('/api/tasks', auth, allow('ADMIN', 'MANAGER'), async (req, res, next) => { try { const { title, description, assignedTo, priority, status, deadline } = req.body; if (!title?.trim() || !description?.trim() || !assignedTo || !deadline) return res.status(400).json({ message: 'Title, description, assignee, and deadline are required' }); if (mongo) return res.status(201).json(await (await Task.create({ title, description, assignedTo, createdBy: req.user._id, priority, status, deadline })).populate('assignedTo createdBy', 'name email')); const task = { id: String(Date.now()), title, description, assignedTo, createdBy: req.user.id, priority: priority || 'MEDIUM', status: status || 'TODO', deadline, createdAt: new Date(), updatedAt: new Date() }; tasks.push(task); res.status(201).json(task) } catch (error) { next(error) } })
app.put('/api/tasks/:id', auth, async (req, res, next) => { try { const updates = {}; ['title', 'description', 'assignedTo', 'priority', 'status', 'deadline'].forEach((key) => { if (req.body[key] !== undefined) updates[key] = req.body[key] }); if (mongo) return res.json(await Task.findByIdAndUpdate(req.params.id, updates, { new: true, runValidators: true })); const task = tasks.find((item) => item.id === req.params.id); if (!task) return res.status(404).json({ message: 'Task not found' }); if (req.user.role === 'EMPLOYEE' && updates.assignedTo) delete updates.assignedTo; Object.assign(task, updates, { updatedAt: new Date() }); res.json(task) } catch (error) { next(error) } })
app.delete('/api/tasks/:id', auth, allow('ADMIN', 'MANAGER'), async (req, res, next) => { try { if (mongo) { await Task.findByIdAndDelete(req.params.id); return res.status(204).end() } const index = tasks.findIndex((item) => item.id === req.params.id); if (index < 0) return res.status(404).json({ message: 'Task not found' }); tasks.splice(index, 1); res.status(204).end() } catch (error) { next(error) } })
app.get('/api/reports', auth, async (req, res, next) => { try { const list = mongo ? await Task.find() : tasks; res.json({ total: list.length, completed: list.filter((task) => task.status === 'COMPLETED').length, inProgress: list.filter((task) => task.status === 'IN_PROGRESS').length, pending: list.filter((task) => task.status === 'TODO').length, overdue: list.filter((task) => task.status === 'OVERDUE').length, highPriority: list.filter((task) => ['HIGH', 'URGENT'].includes(task.priority)).length }) } catch (error) { next(error) } })
app.use((req, res) => res.status(404).json({ message: 'Route not found' })); app.use((error, req, res, next) => { console.error(error.message); res.status(500).json({ message: 'Something went wrong on the server' }) })
if (process.env.MONGODB_URI) mongoose.connect(process.env.MONGODB_URI).then(() => { mongo = true; app.listen(PORT, () => console.log(`Northstar API listening on ${PORT}`)) }).catch(async () => { console.warn('MongoDB unavailable; using development memory store'); await seedDevelopmentStore(); app.listen(PORT, () => console.log(`Northstar API listening on ${PORT}`)) }); else seedDevelopmentStore().then(() => app.listen(PORT, () => console.log(`Northstar API listening on ${PORT} using memory store`)))
